name-template: 'v$RESOLVED_VERSION:'
tag-template: 'v$RESOLVED_VERSION'

# The categories each label corresponds to
category-template: "### $TITLE"
categories:
  - title: '🚀 Features'
    labels:
      - 'Type: Enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'Type: Bug'
  - title: '🧰 Maintenance'
    labels:
      - 'Type: Update (Dependency)'

# Exclude PRs targeting documentation (Wiki) and GitHub Actions
exclude-labels:
  - 'Target: Documentation'
  - 'Target: GitHub Action'

autolabeler:
  - label: 'Target: Documentation'
    files:
      - 'wiki/*.md'
      - '*.md'

change-template: '- $TITLE (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

version-resolver:
  major:
    labels:
      - 'Action: Update Major'
  minor:
    labels:
      - 'Action: Update Minor'
  patch:
    labels:
      - 'Action: Update Patch'
  default: patch

template: '$CHANGES'
