name: Bug Report
description: Found a Bug in OneVersionRemake? Use this template to report it!
labels:
- "Type: Bug"
body:
- type: markdown
  attributes:
    value: |-
      Thank you for taking your time and opening a Bug Report.
      In order for us to process this Bug Report as fast and efficient as possible do we ask you to read the form carefully and provide any requested information.
      Required fields are marked with an asterisk symbol (`*`)
      
      Also, always make sure to use the latest Release from [Spigot](https://www.spigotmc.org/resources/71727/) or the latest [development build](https://ci.codemc.io/job/Andre601/job/OneVersionRemake/) to make sure that your issue isn't already fixed.
- type: checkboxes
  attributes:
    label: Confirmation
    description: "Please make sure to have followed the following checks."
    options:
      - label: "My issue isn't already found on the Issue tracker."
        required: true
      - label: "I use the latest release or development build of the plugin."
- type: dropdown
  attributes:
    label: "Platform"
    description: |-
      What platform (Proxy) do you use?  
      Please mention the platform when you select "Other".
    multiple: false
    options:
      - "BungeeCord"
      - "Waterfall"
      - "Flamecord"
      - "Travertine"
      - "Velocity v1.x"
      - "Velocity v3.x"
      - "Other"
  validations:
    required: true
- type: input
  attributes:
    label: "Other Proxy platform (Optional)"
    description: "Provide the name of the proxy you use, if you selected 'Other' in the previous section." 
- type: textarea
  attributes:
    label: "What happens?"
    description: "What bug are you encountering? Try to explain it as detailed as possible."
    placeholder: "OneVersionRemake does this when I do that..."
  validations:
    required: true
- type: textarea
  attributes:
    label: "Expected Behaviour"
    description: "What behaviour did you expect from OneVersionRemake?"
    placeholder: "OneVersionRemake should actually do..."
  validations:
    required: true
- type: textarea
  attributes:
    label: "How to Reproduce"
    description: "List the steps on how to reproduce this Bug."
    placeholder: |-
      1. Do this
      2. ...
      3. Profit!
  validations:
    required: true
- type: input
  id: "console"
  attributes:
    label: "Console Log"
    description: |-
      Get the latest content of your `latest.log` file an upload it to https://paste.helpch.at
      Take the generated URL and paste it into this field.
    placeholder: "https://paste.helpch.at/latest.log"
- type: input
  id: "error"
  attributes:
    label: "Errors"
    description: |-
      Upload any errors you find to https://paste.helpch.at and post the link in the field below.
    placeholder: "https://paste.helpch.at/error.log"
- type: textarea
  attributes:
    label: "Additional Info"
    description: "Add any extra info you think is nessesary for this Bug report."
    placeholder: "Put any extra info you like into this field..."
