#################################################################################
# +---------------------------------------------------------------------------+ #
# |       ____ _    ______                                                    | #
# |      / __ \ |  / / __ \                               OneVersionRemake    | #
# |     / / / / | / / /_/ /                                   by Andre_601    | #
# |    / /_/ /| |/ / _, _/                                                    | #
# |    \____/ |___/_/ |_|                                                     | #
# |                                                                           | #
# |    GitHub: https://github.com/Andre601/OneVersionRemake                   | #
# |    Spigot: https://spigotmc.org/resources/71727/                          | #
# |    Wiki:   https://ovr.andre601.ch                                        | #
# |                                                                           | #
# +---------------------------------------------------------------------------+ #
#################################################################################
#
# Created with Version ${project.version}
#
# +----------------------------------------------------------------------------+
# |                               Main Settings                                |
# |                                                                            |
# | Main Settings for the plugin.                                              |
# |                                                                            |
# | https://ovr.andre601.ch/config#settings                                    |
# +----------------------------------------------------------------------------+
Settings:
  # +--------------------------------------------------------------------------+
  # | Whether OneVersionRemake should download the latest versions.json on     |
  # | Proxy (re)start.                                                         |
  # |                                                                          |
  # | https://ovr.andre601.ch/config#updateversions                            |
  # +--------------------------------------------------------------------------+
  UpdateVersions: true
  # +--------------------------------------------------------------------------+
  # | URL pointing to the file that contains the different Protocols OVR       |
  # | should use.                                                              |
  # |                                                                          |
  # | https://ovr.andre601.ch/config#versionsurl                               |
  # +--------------------------------------------------------------------------+
  VersionsUrl: 'https://andre601.ch/oneversionremake/protocol_versions.json'

# +----------------------------------------------------------------------------+
# |                             Protocol Settings                              |
# |                                                                            |
# | Protocol Settings for the plugin.                                          |
# |                                                                            |
# | https://ovr.andre601.ch/config#protocol                                    |
# +----------------------------------------------------------------------------+
Protocol:
  # +--------------------------------------------------------------------------+
  # | The Protocol Versions that should be allowed to join the network.        |
  # |                                                                          |
  # | https://ovr.andre601.ch/config#versions                                  |
  # +--------------------------------------------------------------------------+
  Versions: []
  
  # +--------------------------------------------------------------------------+
  # | Should OneVersionRemake log denied Logins in the console?                |
  # |                                                                          |
  # | https://ovr.andre601.ch/config#logdenial                                 |
  # +--------------------------------------------------------------------------+
  LogDenial: true
  
  # +--------------------------------------------------------------------------+
  # | Should the {version} placeholder only show major MC versions?            |
  # |                                                                          |
  # | https://ovr.andre601.ch/config#majoronly                                 |
  # +--------------------------------------------------------------------------+
  MajorOnly: false
  # +--------------------------------------------------------------------------+
  # | Should the list of protocols be treated as a Blacklist?                  |
  # | If set to true, only protocol versions NOT in the list will be allowed.  |
  # |                                                                          |
  # | https://ovr.andre601.ch/config#blacklist                                 |
  # +--------------------------------------------------------------------------+
  Blacklist: false

# +----------------------------------------------------------------------------+
# |                                  Messages                                  |
# |                                                                            |
# | This section contains all the messages that you can configure.             |
# |                                                                            |
# | https://ovr.andre601.ch/config#messages                                    |
# +----------------------------------------------------------------------------+
Messages:
  # +--------------------------------------------------------------------------+
  # | Message to display instead of the Player count (<online>/<max>) next to  |
  # | the ping icon.                                                           |
  # |                                                                          |
  # | https://ovr.andre601.ch/config#playercount                               |
  # +--------------------------------------------------------------------------+
  PlayerCount: '<red>Minecraft {version}'
  
  # +--------------------------------------------------------------------------+
  # | Reason to display, when the player gets kicked for using a unsupported   |
  # | Minecraft Version.                                                       |
  # |                                                                          |
  # | https://ovr.andre601.ch/config#kick                                      |
  # +--------------------------------------------------------------------------+
  Kick:
  - '<red>You are using an unsupported version of Minecraft ({userVersion})!'
  - '<red>This server supports the following Versions:'
  - '<gray>{version}'
  - ''
  - '<red>Please change your Version and try again.'

  # +--------------------------------------------------------------------------+
  # | Message to show when the player hovers over the player count with his    |
  # | cursor.                                                                  |
  # |                                                                          |
  # | https://ovr.andre601.ch/config#hover                                     |
  # +--------------------------------------------------------------------------+
  Hover:
  - '<red>You are using an unsupported version of Minecraft ({userVersion})!'
  - '<red>Please change your version to {version}.'

  # +--------------------------------------------------------------------------+
  # | Message to display in the MOTD of the server.                            |
  # |                                                                          |
  # | https://ovr.andre601.ch/config#motd                                      |
  # +--------------------------------------------------------------------------+
  Motd:
  - '<red>Unsupported Minecraft Version {userVersion}'
  - '<red>Please use <gray>{version}</gray>.'
