name: Build Jar

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Set up JDK 1.11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11.0.10+9'
    - name: Build jar
      run: mvn clean install
    - name: Upload jar
      uses: AButler/upload-release-assets@v2.0
      with:
        files: 'bungeecord/target/OneVersionRemake-*.jar;velocity/target/OneVersionRemake-*.jar;velocity-legacy/target/OneVersionRemake-*.jar'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
