name: Publish wiki

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/wiki.yml'
      - 'docs/**'
      - 'mkdocs.yml'
      - 'requirements.txt'

permissions:
  actions: read
  contents: read
  pages: write
  id-token: write

concurrency:
  group: github-pages
  cancel-in-progress: false

jobs:
  buildSite:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Setup Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Update Pip and install dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
      - name: Build Site
        run: mkdocs build
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: 'site/'
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment