name: Update Wiki

on:
  workflow_dispatch:
  push:
    paths:
      - 'wiki/**'
    branches:
      - 'master'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: SwiftDocOrg/github-wiki-publish-action@v1
      with:
        path: 'wiki'
      env:
        GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.PAT }}
